language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21
    
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - android-sdk-license-c81a61d9
script:
   - ./gradlew :library:test
after_script:
   - ./gradlew :library:uploadArchives
